# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: create stack
          command: |
            aws cloudformation create-stack --stack-name locations \
            --region us-east-1 \
            --template-body file://../aws-cf/template.yml \
            --parameters file://aws-cf/template-param.json \
            --capabilities CAPABILITY_NAMED_IAM

  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello"

  print_world:
    docker:
      - image: circleci/node:13.8.0
    environment:
      URL: << pipeline.project.git_url >>
    steps:
      - run: echo $URL


workflows:
  #welcome:
    # Run the welcome/run job in its own container
    #jobs:
     # - print_hello
      #- print_world:
       #   requires:
        #    - print_hello
  iaas:
    jobs:
     - create_infrastructure