openapi: 3.0.3
info:
  title: Location Service
  description: Service for manipulate user location
  version: "1.0"
servers:
- url: http://localhost:8000
  description: user hosts the User Service.
- url: https://v1.goa.design
  description: user hosts the User Service.
  variables:
    version:
      default: v1
paths:
  /location/now:
    get:
      tags:
      - locations
      summary: now locations
      description: List all stored users
      operationId: locations#now
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
              example:
                country: ehabterra@hotmail.com
                date: Ehab
                time: Terra
components:
  schemas:
    Location:
      type: object
      properties:
        country:
          type: string
          description: User country
          example: ehabterra@hotmail.com
          pattern: .+@.+\..{1,6}
        date:
          type: string
          description: User current date
          example: Ehab
          maxLength: 100
        time:
          type: string
          description: User current time
          example: Terra
          maxLength: 100
      example:
        country: ehabterra@hotmail.com
        date: Ehab
        time: Terra
      required:
      - country
      - date
      - time
