openapi: 3.0.3
info:
  title: Location Service
  description: Service for manipulate locations
  version: "1.0"
servers:
- url: http://localhost:8000
  description: location hosts the Locations Service.
- url: https://v1.goa.design
  description: location hosts the Locations Service.
  variables:
    version:
      default: v1
paths:
  /location/now:
    get:
      tags:
      - locations
      summary: now locations
      description: Get client IP location
      operationId: locations#now
      parameters:
      - name: X-Forwarded-For
        in: header
        allowEmptyValue: true
        schema:
          type: string
          example: Beatae nostrum sit numquam mollitia qui.
        example: Pariatur quia sed aut voluptatem rem dolorum.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
              example:
                country: Egypt
                date: dd-mm-yyyy
                time: hh:mm:ss
components:
  schemas:
    Location:
      type: object
      properties:
        country:
          type: string
          description: User country
          example: Egypt
        date:
          type: string
          description: User current date
          example: dd-mm-yyyy
        time:
          type: string
          description: User current time
          example: hh:mm:ss
      example:
        country: Egypt
        date: dd-mm-yyyy
        time: hh:mm:ss
      required:
      - country
      - date
      - time
